language: node_js
node_js:
    - '10'
install:
    - npm install
script:
    - npm test && npm run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    project: ./dist/
    local_dir: ./dist/
    on:
        branch: master
